# Generated by Django 3.2.5 on 2021-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('icon', models.CharField(default='', max_length=250)),
                ('url', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
