# Generated by Django 3.2.5 on 2021-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_temp', models.FloatField(default=0.0)),
                ('air_temp', models.FloatField(default=0.0)),
                ('soil_moisture', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='plant_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
