# Generated by Django 3.2.5 on 2021-09-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210904_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='Detail',
        ),
    ]
