# Generated by Django 3.2.5 on 2021-09-07 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_location_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_temp', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='livesensordata',
            name='lat',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='livesensordata',
            name='lng',
            field=models.CharField(default='', max_length=250),
        ),
    ]
