# Generated by Django 3.2.5 on 2021-09-07 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210907_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_temp', models.FloatField(default=0.0)),
                ('air_temp', models.FloatField(default=0.0)),
                ('soil_moisture', models.FloatField(default=0.0)),
                ('lat', models.CharField(default='', max_length=250)),
                ('lng', models.CharField(default='', max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='livesensordata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
