# Generated by Django 3.2.5 on 2021-09-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210907_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveSensorData',
        ),
    ]
