# Generated by Django 3.2.5 on 2021-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_delete_livesensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorhisdata',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='sensorhisdata',
            name='lng',
        ),
        migrations.AlterField(
            model_name='sensorhisdata',
            name='date',
            field=models.IntegerField(verbose_name=1631045317000),
        ),
    ]
