# Generated by Django 3.2.5 on 2021-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210907_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorhisdata',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
